// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetAppConfig():Promise<{[key: string]: any}>;

export function GetCpuCores():Promise<number>;

export function OpenOutputDir():Promise<void>;

export function RestoreDefaults():Promise<void>;

export function SetConfig(arg1:string):Promise<void>;

export function SetLastDir(arg1:string):Promise<void>;

export function SetOutDir():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
