// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['videoManager']['VideoManager']['AddFiles']();
}

export function Clear() {
  return window['go']['videoManager']['VideoManager']['Clear']();
}

export function Debug(arg1) {
  return window['go']['videoManager']['VideoManager']['Debug'](arg1);
}

export function StartReencoding() {
  return window['go']['videoManager']['VideoManager']['StartReencoding']();
}

export function Startup(arg1) {
  return window['go']['videoManager']['VideoManager']['Startup'](arg1);
}

export function StopReencoding() {
  return window['go']['videoManager']['VideoManager']['StopReencoding']();
}
