// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {videoManager} from '../models';
import {context} from '../models';

export function AddFiles():Promise<string>;

export function Clear():Promise<void>;

export function Debug(arg1:string):Promise<videoManager.VideoFileInfo>;

export function StartReencoding():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopReencoding():Promise<void>;
