// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['imageManager']['ImageManager']['AddFiles']();
}

export function Clear() {
  return window['go']['imageManager']['ImageManager']['Clear']();
}

export function Debug() {
  return window['go']['imageManager']['ImageManager']['Debug']();
}

export function StartConversion() {
  return window['go']['imageManager']['ImageManager']['StartConversion']();
}

export function Startup(arg1) {
  return window['go']['imageManager']['ImageManager']['Startup'](arg1);
}

export function StopConversion() {
  return window['go']['imageManager']['ImageManager']['StopConversion']();
}
