// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {imageManager} from '../models';
import {context} from '../models';

export function AddFiles():Promise<imageManager.SessionData>;

export function Clear():Promise<void>;

export function Debug():Promise<boolean>;

export function StartConversion():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopConversion():Promise<void>;
